### ISSUE TITLE
Postfix Completion setting fail

### ISSUE THREAD

**Issue by Hoysion** [LiLittleCat/intellij-generate-all-getter-and-setter#1]
When enable the plugin,Postfix Completion has two java group,the second java group is useful,but just can set the only one template

Such as setting the first template in the second java group and click ok,it is useful

When i setting the second template in the seconde java group and click ok,when i reopen the window,not only the seconde template and the first template is removed

Please fix this,Thank u
![image](https://user-images.githubusercontent.com/57893875/165267587-e9f0585d-362f-4326-8fe9-89aace73b246.png)

**Comment by LiLittleCat** [comment]
Fixed with version 1.0.1, thanks for using this plugin.
