### ISSUE TITLE
Support generate get methods include starts with 'is' 

### ISSUE THREAD

**Issue by Hoysion** [LiLittleCat/intellij-generate-all-getter-and-setter#4]
click the all getter also generate methods include starts with 'is'

**Comment by Maroko** [comment]
I've generated getter and setter for boolean and Boolean:

```
private boolean name;
private Boolean name2;

public boolean isName() {
return name;
}

public void setName(boolean name) {
this.name = name;
}

public Boolean getName2() {
return name2;
}

public void setName2(Boolean name2) {
this.name2 = name2;
}
```

**Comment by Hoysion** [comment]
It is!Supoort!Thanks!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Tatu ***@***.***&gt;; 
发送时间: 2022年8月12日(星期五) 下午5:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [LiLittleCat/intellij-generate-all-getter-and-setter] Support generate get methods include starts with &#39;is&#39;  (Issue #4)





 
I've generated getter and setter for boolean and Boolean:
 private boolean name; private Boolean name2; public boolean isName() { return name; } public void setName(boolean name) { this.name = name; } public Boolean getName2() { return name2; } public void setName2(Boolean name2) { this.name2 = name2; }

**Comment by LiLittleCat** [comment]
@Maroko Thanks, I got it. 
@Hoysion I will support that ASAP.

**Comment by LiLittleCat** [comment]
Support in v1.0.6 @Maroko @Hoysion
